name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main        # obrigatório para aplicar Quality Gate
      - develop     # permite rodar análise durante desenvolvimento
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install behave coverage

      - name: Run Behave tests with coverage
        run: |
          coverage run -m behave
          coverage xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarCloud Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@v1
        timeout-minutes: 5
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
